### ISSUE TITLE
CmdStanPy frequently errors out with CmdStan 2.27.0

### ISSUE THREAD

**Issue by jmshoun** [stan-dev/cmdstanpy#388]
#### Summary:

CmdStanPy frequently errors out when used with CmdStan 2.27.0.

#### Description:

The CmdStan 2.27.0 release added a new field `local_datetime` to the metadata in the CSV file header. This new field causes `CmdStanMCMC.validate_csv_files()` to error out very frequently, because the timestamp on the CSV associated with each chain may differ by a few seconds. An example error message (thrown from [here](https://github.com/stan-dev/cmdstanpy/blob/develop/cmdstanpy/stanfit.py#L725)):

```
ValueError: csv file header mismatch, file [Ed: filename omitted], key start_datetime is 2021-06-07 12:45:29 UTC, expected 2021-06-07 12:45:31 UTC
```

The fix seems to be an easy one-liner: just add `local_datetime` to the list of fields [here](https://github.com/stan-dev/cmdstanpy/blob/develop/cmdstanpy/stanfit.py#L721) that are explicitly exempted from matching exactly across all chains. I'm not sure if the Stan team is already aware of the issue, or if there's a better solution to the problem, but I'm happy to create a PR with this fix.

#### Additional Information:

The `validate_csv` flag in the CmdStanMCMC object doesn't offer much relief. My team's analytical workflow depends on the metadata attribute that is populated at the end of the `validate_csv` method. Our current workaround is to set `validate_csv=False` and then manually set `_metadata` in client code, but this still doesn't fix everything because we also rely on `arviz`, which doesn't offer the option to bypass CSV validation.

#### Current Version:

We have this issue with CmdStanPy v0.9.75 and CmdStan v2.27.0.

**Comment by mitzimorris** [comment]
thanks for catching this - will implement fix ASAP!!!

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/cmdstanpy/pull/389

**Comment by mitzimorris** [comment]
fixed in release 0.9.76

**Comment by mortonjt** [comment]
Hello, I'm noticing similar errors with cmdstan-2.30.1 and cmdstanpy-1.0.7

`ValueError: csv file header mismatch, file /tmp/tmpxil3zwbp/nb_case_control_single-202209211457-3-2fs9n7a_.csv, key start_datetime is 2022-09-21 18:57:07 UTC, expected 2022-09-21 18:57:08 UTC`

The error is random, but about 90% of my runs are failing (which wasn't the case for cmdstanpy-0.9.76).
My tests seem to be passing, so I think the underlying code is fine, but perhaps the validation is too stringent? Would it be fruitful to validate within 1 minute rather than to the second?

**Comment by WardBrian** [comment]
@mortonjt I don't believe that exact error message still appears in the package, are you sure you're using 1.0.7 and not an older version? You should be able to verify this with cmdstanpy.show_versions()

**Comment by mortonjt** [comment]
Hi @WardBrian , it turns out that I got my environment mixed up -- I'm not seeing the error anymore.  Thanks.
